In [4]:
# 1
import numpy as np
x = np.arange(11, 30)
print("Original array:")
print(x)
print("Reverse array:")
x = x[::-1]
print(x)

Original array:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Reverse array:
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11]


In [3]:
### 2
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [5]:
### 3
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [0, 40]
print("Array2: ",array2)
print("Compare each element of array1 and array2")
print(np.in1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [0, 40]
Compare each element of array1 and array2
[ True False False  True False]


In [6]:
### 4
import numpy as np
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ",array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ",array2)
print("Unique values in array1 that are not in array2:")
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2:
[ 0 20 60 80]


In [7]:
### 5
import numpy as np
x =  np.diagflat([1, 5, 9, 8])
print(x)

[[1 0 0 0]
 [0 5 0 0]
 [0 0 9 0]
 [0 0 0 8]]
